name: Publish prod image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build main branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # Mise à jour de la distribution
          java-version: '17'

      - name: Maven Build & Sonar analysis
        run: mvn -B verify --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/univ-smb-m1-isc-2023/kwouik-api:latest .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        run: docker push ghcr.io/univ-smb-m1-isc-2023/kwouik-api:latest
